name: EduSaaS AIML CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Pipeline
        run: echo "Pipeline triggered successfully"
